re_configurator_product:
    resource: "@ReConfiguratorBundle/Resources/config/routing/product.yml"
    prefix:   /product

re_configurator_color:
    resource: "@ReConfiguratorBundle/Resources/config/routing/color.yml"
    prefix:   /color

re_configurator_homepage:
    path:     /hello/{name}
    defaults: { _controller: ReConfiguratorBundle:Default:index }

index:
    path:     /
    defaults: { _controller: ReConfiguratorBundle:Homepage:index }
