parameters:
#    re_demo_user.example.class: Re\DemoUserBundle\Example

services:
#    re_demo_user.example:
#        class: %re_demo_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
