accessory:
    pattern:  /
    defaults: { _controller: "ReConfiguratorBundle:Accessory:index" }

accessory_show:
    pattern:  /{id}/show
    defaults: { _controller: "ReConfiguratorBundle:Accessory:show" }

accessory_new:
    pattern:  /new
    defaults: { _controller: "ReConfiguratorBundle:Accessory:new" }

accessory_create:
    pattern:  /create
    defaults: { _controller: "ReConfiguratorBundle:Accessory:create" }
    requirements: { _method: post }

accessory_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ReConfiguratorBundle:Accessory:edit" }

accessory_update:
    pattern:  /{id}/update
    defaults: { _controller: "ReConfiguratorBundle:Accessory:update" }
    requirements: { _method: post|put }

accessory_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ReConfiguratorBundle:Accessory:delete" }
    requirements: { _method: post|delete }
